# Training configuration for ViT
# Example: edit these values as needed

batch_size: 256
num_epochs: 300
learning_rate: 0.0003
weight_decay: 0.1
eta_min: 0.00000000001

use_ldfa_linear: True
ldfa_rank: 32
qp_lr: 0.005
qp_weight_decay: 0.0
qp_eta_min: 0.00000000001


#model specificcations
patch_size: 4
in_chans: 3
embed_dim: 384
depth: 8
num_heads: 8
mlp_ratio: 2.0
qkv_bias: true
drop_rate: 0.1
attn_drop_rate: 0.1
drop_path_rate: 0.1

dataset: cifar100
model_name: vit_s_8_layers_384_fix
image_size: 32
num_classes: 100
log_name: cifar100_lr3e4_wd1e1_bs_256_LDFA_32