# Training configuration for ViT
# Example: edit these values as needed
learning_rate: 0.001
weight_decay: 0.0001 #( 0.00005 was used with exponential decay)
batch_size: 128
num_epochs: 200

use_ldfa_linear: False

dataset: cifar10
model_name: vit_b_16
image_size: 32
num_classes: 10
log_name: default_run_BP_lr_1e3_onecycle_10_epochs_warmpup
