# Training configuration for ViT
# Example: edit these values as needed

batch_size: 256
num_epochs: 400
learning_rate: 0.0003
weight_decay: 0.1
eta_min: 0.0000000001

use_ldfa_linear: True
ldfa_rank: 4
qp_lr: 0.01
qp_weight_decay: 0.0
qp_eta_min: 0.0000000001


#model specificcations
patch_size: 4
in_chans: 3
embed_dim: 384
depth: 8
num_heads: 8
mlp_ratio: 2.0
qkv_bias: true
drop_rate: 0.1
attn_drop_rate: 0.1
drop_path_rate: 0.1

dataset: cifar100
num_subset_classes: 50
model_name: vit_b_16_subsets50
image_size: 32
num_classes: 50
log_name: LDFA_4_lr5e4_wd1e1_bs_256_qp_15e2